### PR TITLE
feat: Address format implementation

### PR DESCRIPTION
**Pull request by xxuejie**

### CODE REVIEW

**Comment by ashchan** [comment]
@classicalliu Could you please add some test cases that other SDKs can follow and confirm?

**Comment by classicalliu** [comment]
> @classicalliu Could you please add some test cases that other SDKs can follow and confirm?

I'll check and work on it

**Comment by classicalliu** [comment]
@ashchan tests added

**Comment by ashchan** [comment]
> @ashchan tests added

Great. Looks good.

**Comment by ashchan** [comment]
@classicalliu We have some conflicts.

**Pull request merged**
